In [1]:
import torch

In [9]:
scalar = torch.tensor(7)
scalar.ndim

0

In [12]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [14]:
vector.ndim
vector.shape

torch.Size([2])

In [16]:
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [34]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
# Create a random tnesor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7905, 0.9213, 0.8299, 0.8552],
        [0.1730, 0.0367, 0.3033, 0.1841],
        [0.7812, 0.8594, 0.4933, 0.4311]])

In [72]:
zero_to_nine = torch.arange(0, 10)
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
ten_zeros = torch.zeros_like(zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
# Floar 32 tensor
float_16_tensor = torch.tensor([1, 2, 3], 
                                dtype=torch.half, # what data  type is the tensor
                                device='cuda', # default: device=None which is same as device="cpu"
                                requires_grad=False #wether or not to track gradients qith this tensors operations)
float_16_tensor.device

device(type='cuda', index=0)

In [92]:
float_64_tensor = float_16_tensor.type(torch.double)
float_64_tensor.dtype

torch.float64

In [99]:
float_16_tensor * float_64_tensor

tensor([1., 4., 9.], device='cuda:0', dtype=torch.float64)